name: flutter_masked_text
description: Masked text input for flutter.
version: 0.8.0
author: Ben-hur Santos Ott <ben-hur@outlook.com>
homepage: https://github.com/benhurott/flutter-masked-text

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

environment:
    sdk: '>=1.23.0 <3.0.0'
flutter: